// <auto-generated />
using System;
using Kiemtragiuaky.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kiemtragiuaky.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kiemtragiuaky.Models.ChiTietDangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .HasColumnType("integer");

                    b.Property<int>("MaHP")
                        .HasColumnType("integer");

                    b.Property<string>("HocPhanMaHP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaDK", "MaHP");

                    b.HasIndex("HocPhanMaHP");

                    b.ToTable("ChiTietDangKy");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDK"));

                    b.Property<long>("MaSV")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SinhVienMaSV")
                        .HasColumnType("bigint");

                    b.HasKey("MaDK");

                    b.HasIndex("SinhVienMaSV");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHP")
                        .HasColumnType("text");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("integer");

                    b.Property<string>("TenHP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaHP");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasColumnType("text");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaNganh");

                    b.ToTable("NganhHoc");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.SinhVien", b =>
                {
                    b.Property<long>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MaSV"));

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaSV");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.ChiTietDangKy", b =>
                {
                    b.HasOne("Kiemtragiuaky.Models.HocPhan", "HocPhan")
                        .WithMany("ChiTietDangKy")
                        .HasForeignKey("HocPhanMaHP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kiemtragiuaky.Models.DangKy", "DangKy")
                        .WithMany("ChiTietDangKy")
                        .HasForeignKey("MaDK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.DangKy", b =>
                {
                    b.HasOne("Kiemtragiuaky.Models.SinhVien", "SinhVien")
                        .WithMany("DangKy")
                        .HasForeignKey("SinhVienMaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.SinhVien", b =>
                {
                    b.HasOne("Kiemtragiuaky.Models.NganhHoc", "NganhHoc")
                        .WithMany("SinhVien")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_MaNganh");

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.DangKy", b =>
                {
                    b.Navigation("ChiTietDangKy");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.HocPhan", b =>
                {
                    b.Navigation("ChiTietDangKy");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Kiemtragiuaky.Models.SinhVien", b =>
                {
                    b.Navigation("DangKy");
                });
#pragma warning restore 612, 618
        }
    }
}
